/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stock_managment_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Bryan
 */
public class restricted_loging extends javax.swing.JFrame {

    /**
     * Creates new form restricted_loging
     */
    public restricted_loging() {
        initComponents();
    }
Connection Con = null;
  Statement St = null;
  ResultSet Rs = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_restricted = new javax.swing.JTextField();
        lbl_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txt_restricted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_restrictedActionPerformed(evt);
            }
        });
        txt_restricted.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_restrictedKeyPressed(evt);
            }
        });

        lbl_back.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_back.setText("<--");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_restricted, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_restricted, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_restrictedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_restrictedKeyPressed
       if(txt_restricted.getText().equals("Bryan")){
        if (evt.getKeyChar() == '`') {
            dispose();
            new admin_management().setVisible(true);
        } else {
//             Date now = new Date();
//             SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//              String formattedDate = formatter.format(now);
//              try{
//            Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_managment", "root", "");
//            PreparedStatement add = Con.prepareStatement("INSERT INTO restrictedarea VALUES (?)");
//            add.setString(1, formattedDate);
//            int row = add.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Restricted Area! Login attempt failed and recorded. Current date and time: " + formattedDate);
//            
//            
//        }
//        catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(this, e);  
//        }
        }
       }
    
       
    }//GEN-LAST:event_txt_restrictedKeyPressed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        dispose();
        new loging_page().setVisible(true);
    }//GEN-LAST:event_lbl_backMouseClicked

    private void txt_restrictedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_restrictedActionPerformed
         Date now = new Date();
             SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
              String formattedDate = formatter.format(now);
              try{
            Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_managment", "root", "");
            PreparedStatement add = Con.prepareStatement("INSERT INTO restrictedarea VALUES (?)");
            add.setString(1, formattedDate);
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Restricted Area! Login attempt failed and recorded. Current date and time: " + formattedDate);
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);  
        }
    }//GEN-LAST:event_txt_restrictedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(restricted_loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(restricted_loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(restricted_loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(restricted_loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restricted_loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_back;
    private javax.swing.JTextField txt_restricted;
    // End of variables declaration//GEN-END:variables
}
