/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stock_managment_system;

/**
 *
 * @author Bryan
 */
public class stock_manager_manual extends javax.swing.JFrame {

    /**
     * Creates new form stock_manager_manual
     */
    public stock_manager_manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_stock_management = new javax.swing.JButton();
        btn_category_management = new javax.swing.JButton();
        btn_stock_transaction = new javax.swing.JButton();
        lbl_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 112));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Manager");

        btn_stock_management.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_stock_management.setForeground(new java.awt.Color(0, 0, 112));
        btn_stock_management.setText("Stock Management");
        btn_stock_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stock_managementMouseClicked(evt);
            }
        });
        btn_stock_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stock_managementActionPerformed(evt);
            }
        });

        btn_category_management.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_category_management.setForeground(new java.awt.Color(0, 0, 112));
        btn_category_management.setText("Category Management");
        btn_category_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_category_managementMouseClicked(evt);
            }
        });
        btn_category_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_category_managementActionPerformed(evt);
            }
        });

        btn_stock_transaction.setBackground(new java.awt.Color(0, 0, 112));
        btn_stock_transaction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_stock_transaction.setForeground(new java.awt.Color(0, 0, 112));
        btn_stock_transaction.setText("Stock Transactions");
        btn_stock_transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stock_transactionMouseClicked(evt);
            }
        });
        btn_stock_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stock_transactionActionPerformed(evt);
            }
        });

        lbl_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back.setText("<--");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_stock_management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_category_management, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(btn_stock_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btn_stock_management)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_category_management)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_stock_transaction)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_stock_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stock_managementMouseClicked
        
        new stock_management().setVisible(true);
    }//GEN-LAST:event_btn_stock_managementMouseClicked

    private void btn_stock_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stock_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stock_managementActionPerformed

    private void btn_category_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_category_managementMouseClicked
       
        new category_management().setVisible(true);
    }//GEN-LAST:event_btn_category_managementMouseClicked

    private void btn_category_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_category_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_category_managementActionPerformed

    private void btn_stock_transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stock_transactionMouseClicked
        
//        new stock_transaction().setVisible(true);
    }//GEN-LAST:event_btn_stock_transactionMouseClicked

    private void btn_stock_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stock_transactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stock_transactionActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        dispose();
        new loging_page().setVisible(true);
    }//GEN-LAST:event_lbl_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_manager_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_manager_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_manager_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_manager_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_manager_manual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_category_management;
    private javax.swing.JButton btn_stock_management;
    private javax.swing.JButton btn_stock_transaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_back;
    // End of variables declaration//GEN-END:variables
}
